### ISSUE TITLE
vmxt terminates when running on CentOS 7.5

### ISSUE THREAD

**Issue by mwiget** [Juniper/OpenJNPR-Container-vMX#4]
```
$ uname -a
Linux ESXi.fritz.box 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[mwiget@ESXi vmx]$ cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
$
```

Tried vMX 18.3 and earlier versions and they don't get fpc up and running. RIOT is running but vmxt isn't. Seems to be a kernel related issue? 

Ubuntu  uses kernel version 4.x and there vMX 18.3 (and earlier)versions run fine.

```
$ uname -a
Linux sb 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mwiget** [comment]
Hmm. Upgraded kernel to 4.x and the issue remains, vmxt doesn't run within the container:

```
$ uname -a
Linux s1.fritz.box 4.18.11-1.el7.elrepo.x86_64 #1 SMP Sat Sep 29 09:42:38 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/meminfo |grep Huge
AnonHugePages:   1423360 kB
ShmemHugePages:        0 kB
HugePages_Total:       5
HugePages_Free:        4
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:    1048576 kB
Hugetlb:         5242880 kB
$ docker -v
Docker version 18.06.1-ce, build e68fc7a
]$
```

```
--- JUNOS 18.3R1.9 Kernel 64-bit  JNPR-11.0-20180816.8630ec5_buil
mwiget@vmx1> show chassis fpc
                     Temp  CPU Utilization (%)   CPU Utilization (%)  Memory    Utilization (%)
Slot State            (C)  Total  Interrupt      1min   5min   15min  DRAM (MB) Heap     Buffer
  0  Present          Absent
  1  Empty
  2  Empty
  3  Empty
  4  Empty
  5  Empty
  6  Empty
  7  Empty
  8  Empty
  9  Empty
 10  Empty
 11  Empty
```

**Comment by mwiget** [comment]
Reading the core file with gdb (on another ubuntu 18.04 system, don't have gdb in the container):

```
mwiget@sb:~$ !gdb
gdb vmxt core.2673
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from vmxt...(no debugging symbols found)...done.

warning: core file may not match specified executable file.
[New LWP 2673]
[New LWP 2676]
[New LWP 2675]
[New LWP 2674]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/share/pfe/vmxt -N -C 4'.
Program terminated with signal SIGABRT, Aborted.
#0  0xf7735430 in __kernel_vsyscall ()
[Current thread is 1 (Thread 0xf728a700 (LWP 2673))]
(gdb) where
#0  0xf7735430 in __kernel_vsyscall ()
#1  0xf72b9832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf72bacc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x08084650 in ?? ()
#4  0x080884bc in ?? ()
#5  0x08089366 in ?? ()
#6  0x080893e9 in ?? ()
#7  0x08080a25 in ?? ()
#8  0x0807c330 in ?? ()
#9  0x0807a2f0 in ?? ()
#10 0x080618a3 in ?? ()
#11 0xf72a4e81 in __libc_start_main () from /lib/i386-linux-gnu/libc.so.6
#12 0x08063a0d in ?? ()
```

shared libs:

```
root@dd6a78b00eb1:/# ldd /usr/share/pfe/vmxt
	linux-gate.so.1 (0xf77ac000)
	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf761e000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf751c000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf74fe000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf74df000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7303000)
	/lib/ld-linux.so.2 (0xf77ad000)
```

**Comment by mwiget** [comment]
Same issue with vmxt when running junos-vmx-x86-64-18.1R1.9.qcow2 on juniper/openjnpr-container-vmx:trusty, which is based on Ubuntu 14.04.5 LTS.
